# GitHub Actions workflow to run tests on macOS.
name: "macOS"

on:
  push:
    branches: ["master"]
  pull_request: {}
  schedule:
    - cron: "0 0 * * 0" # At 00:00 weekly on Sunday.

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: "${{ matrix.os }}${{ matrix.libressl && ' +libtls' || '' }}"
    runs-on: "${{ matrix.os }}"
    if: ${{ github.repository_owner == 'openntpd' || github.event_name != 'schedule' }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-15", "macos-14"]
        include:
          - os: "macos-15"
            libressl: true
    steps:
      - name: "Install required packages"
        run: brew install automake libtool ${{ matrix.libressl && 'libressl' || '' }}

      - name: "Checkout repository"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: "Set libressl paths"
        if: matrix.libressl
        run: |
          LIBRESSL_PREFIX=$(brew --prefix libressl)
          echo "CPPFLAGS=-I${LIBRESSL_PREFIX}/include" >> $GITHUB_ENV
          echo "LDFLAGS=-L${LIBRESSL_PREFIX}/lib" >> $GITHUB_ENV

      - name: "autogen"
        run: ./autogen.sh

      - name: "configure"
        run: ./configure

      - name: "make"
        run: make

      - name: "make check"
        run: make check

      - name: "make distcheck"
        run: make distcheck
